[package]
name = "bevy_reflect_fns"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy_reflect = "0.9"
thiserror = "1.0"

[dev-dependencies]
bevy_reflect = { version = "0.9", features = ["glam"] }
glam = "0.22"
